name: Init Vault

on:
  push:
    branches:
      - init-vault
  workflow_dispatch:

jobs:
  send-notification-started:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *🚀 UrTask  - Init Vault  *  🏃‍♂️${{ github.run_number }}

            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Started 🚁️️️️️️🚁️️️️️️🚁️️️️️️🚁️️️️️️

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_K8S_LOCAL }}
          version: "latest"

      - name: Apply Kubernetes deployment
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
          URTASK_BOT_TOKEN: ${{ secrets.URTASK_BOT_TOKEN }}
        run: |
          kubectl exec -n vault -i vault-0 -- vault kv put \
            kv/urtask-dev \
            MONGODB_CONNECTION_STRING="${MONGODB_CONNECTION_STRING}" \
            URTASK_BOT_TOKEN="${URTASK_BOT_TOKEN}"

          kubectl exec -n vault -i vault-0 -- vault policy write urtask-svc-policy - <<EOH
          path "kv/data/urtask-dev" {
            capabilities = ["read"]
          }
          EOH

          kubectl exec -n vault -i vault-0 -- vault write auth/kubernetes/role/urtask-dev \
            bound_service_account_names=urtask-dev-auth \
            bound_service_account_namespaces=urtask \
            policies=urtask-svc-policy \
            ttl=72h

  send-notification-deploy-failed:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ failure() && needs.deploy.result == 'failure' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *❌ UrTask  - Init Vault  *  🏃‍♂️${{ github.run_number }}
            
            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Deploy Failed!!!
            😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️😐️️️️️️

  send-notification-successful:
    needs: deploy
    runs-on: ubuntu-latest
    if: ${{ success() && needs.deploy.result == 'success' }}
    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_GROUP_DEPLOYMENTS }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          disable_web_page_preview: true
          message: |
            *🎉 UrTask  - Init Vault  *  🏃‍♂️${{ github.run_number }}
            
            *👤 Committer:* [${{ github.actor }}](https://github.com/${{ github.actor }})
            *📝 Commit message:* ${{ github.event.commits[0].message }}
            *📦 Repository:* ${{ github.repository }}
            *🔍 See changes:* [View changes](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            Successful
            🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️🚀️️️️️️